
version: '3.8'

x-common-variables: &common-variables
  p

services:
   mysql:
     build: ./db
     environment:
       <<: *common-variables
       MYSQL_HOST: localhost
       MYSQL_ROOT_PASSWORD: root
     ports:
     - 3307:3306
   server:
     build: ./server
     depends_on:
       - mysql
     expose:
       - 8000
     environment:
       <<: *common-variables
       MYSQL_HOST_IP: mysql
     ports:
       - 8000:8000
   client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - "8080:3000"
    volumes:
      - ./client/src:/app/src
    links:
      - server